-- MySQL Script generated by MySQL Workbench
-- Tue Dec  8 12:54:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Elecciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Elecciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Elecciones` DEFAULT CHARACTER SET utf8 ;
USE `Elecciones` ;

-- -----------------------------------------------------
-- Table `Elecciones`.`Ciudadanos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elecciones`.`Ciudadanos` (
  `cedula` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Elecciones`.`Partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elecciones`.`Partidos` (
  `id_partido` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(256) NOT NULL,
  `logo` VARCHAR(45) NULL,
  `estado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_partido`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Elecciones`.`Puestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elecciones`.`Puestos` (
  `id_puesto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(256) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_puesto`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Elecciones`.`Candidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elecciones`.`Candidatos` (
  `id_candidato` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `id_partido` INT NOT NULL,
  `id_puesto` INT NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_candidato`),
  INDEX `fk_Candidatos_Partidos_idx` (`id_partido` ASC) ,
  INDEX `fk_Candidatos_Puestos_idx` (`id_puesto` ASC) ,
  CONSTRAINT `fk_Candidatos_Partidos`
    FOREIGN KEY (`id_partido`)
    REFERENCES `Elecciones`.`Partidos` (`id_partido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidatos_Puestos`
    FOREIGN KEY (`id_puesto`)
    REFERENCES `Elecciones`.`Puestos` (`id_puesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Elecciones`.`Elecciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elecciones`.`Elecciones` (
  `id_elecciones` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_elecciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Elecciones`.`Votaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elecciones`.`Votaciones` (
  `id_elecciones` INT NOT NULL,
  `id_candidato` INT NOT NULL,
  `id_partido` INT NOT NULL,
  `id_puesto` INT NOT NULL,
  `cedula` VARCHAR(30) NOT NULL,
  INDEX `fk_Votaciones_Elecciones_idx` (`id_elecciones` ASC) ,
  INDEX `fk_Votaciones_Candidatos_idx` (`id_candidato` ASC) ,
  INDEX `fk_Votaciones_Partidos_idx` (`id_partido` ASC) ,
  INDEX `fk_Votaciones_Puestos_idx` (`id_puesto` ASC) ,
  INDEX `fk_Votaciones_Ciudadanos_idx` (`cedula` ASC) ,
  PRIMARY KEY (`id_elecciones`, `cedula`, `id_puesto`, `id_candidato`),
  CONSTRAINT `fk_Votaciones_Elecciones`
    FOREIGN KEY (`id_elecciones`)
    REFERENCES `Elecciones`.`Elecciones` (`id_elecciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votaciones_Candidatos`
    FOREIGN KEY (`id_candidato`)
    REFERENCES `Elecciones`.`Candidatos` (`id_candidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votaciones_Partidos`
    FOREIGN KEY (`id_partido`)
    REFERENCES `Elecciones`.`Partidos` (`id_partido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votaciones_Puestos`
    FOREIGN KEY (`id_puesto`)
    REFERENCES `Elecciones`.`Puestos` (`id_puesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votaciones_Ciudadanos`
    FOREIGN KEY (`cedula`)
    REFERENCES `Elecciones`.`Ciudadanos` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Elecciones`.`Administracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elecciones`.`Administracion` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Administracion_Ciudadanos_idx` (`cedula` ASC) ,
  CONSTRAINT `fk_Administracion_Ciudadanos`
    FOREIGN KEY (`cedula`)
    REFERENCES `Elecciones`.`Ciudadanos` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Ciudadanos(cedula, nombre, apellido, email, estado) VALUES ('40200745277','Andy Jose','Peña Minyety','andyminyety@hotmail.com',1);
INSERT INTO Administracion(usuario, clave, nombre, apellido, cedula) VALUES ('admin','12345','Andy Jose','Peña Minyety','40200745277');
INSERT INTO Puestos(id_puesto, nombre, descripcion, estado) VALUES (1,'Presidente','Es la persona designada profesionalmente para dirigir un Gobierno.',1);
INSERT INTO Partidos(id_partido, nombre, descripcion, logo, estado) VALUES (1,'Voto Nulo','Ninguno','Nulo.png',1);
INSERT INTO Candidatos(id_candidato, nombre, apellido, id_partido, id_puesto, foto, estado) VALUES (1,'Voto','Nulo',1,1,'Genérico.jpeg',1);